version: "3"

services:
  cpass-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://root:password@db:5432/cpass
      - PORT=8080
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cpass
