services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        environment:
            - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_DATABASE}
            - PORT=8080
        restart: always
        depends_on:
            - db

    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        restart: always
        depends_on:
            - api

    db:
        image: postgres
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_DATABASE}
