services:
  http:
    image: ghcr.io/cyberfatherrt/cpass_http
    build:
      context: .
      target: final-http
    secrets:
      - db-password
    environment:
      - ADDR=0.0.0.0:8000
      - DB_PASSWORD_FILE=/run/secrets/db-password
    depends_on:
      - db
    deploy:
      replicas: 9
      placement:
        constraints: [node.role == worker]
        max_replicas_per_node: 3

  grpc:
    image: ghcr.io/cyberfatherrt/cpass_grpc
    build:
      context: .
      target: final-grpc
    secrets:
      - db-password
    environment:
      - ADDR=0.0.0.0:50051
      - DB_PASSWORD_FILE=/run/secrets/db-password
    depends_on:
      - db
    deploy:
      replicas: 9
      placement:
        constraints: [node.role == worker]
        max_replicas_per_node: 3

  proxy_worker:
    image: ghcr.io/cyberfatherrt/cpass_proxy_worker
    build:
      context: proxy
      args:
        role: worker
    depends_on:
      - http
      - grpc
    deploy:
      placement:
        constraints: [node.role == worker]

  proxy_manager:
    image: ghcr.io/cyberfatherrt/cpass_proxy_manager
    build:
      context: proxy
      args:
        role: manager
    ports:
      - 80:80
      - 443:443
      - 50051:50051
    depends_on:
      - proxy_worker
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  db:
    image: postgres:16.3-alpine3.20
    user: postgres
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=cpass
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    deploy:
      placement:
        constraints: [node.role == manager]

secrets:
  db-password:
    file: secrets/db-password.txt
