FROM node:21.5.0-alpine3.19 AS builder
WORKDIR /app

COPY package.json package.json
RUN npm install

COPY . .
RUN npm run build


FROM busybox:1.36.1-musl
WORKDIR /app

COPY --from=builder /app/build /app/build

ENTRYPOINT [ "busybox", "httpd", "-f", "-v", "-p", "8000", "-h", "build"]
