services:
  http:
    image: ghcr.io/cyberfatherrt/cpass_http
    build:
      context: .
      target: final-http
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
    environment:
      - ADDR=0.0.0.0:8000
      - DATABASE_URL=postgres://postgres:pass@db:5432/cpass
    depends_on:
      - db
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]

  grpc:
    image: ghcr.io/cyberfatherrt/cpass_grpc
    build:
      context: .
      target: final-grpc
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
    environment:
      - ADDR=0.0.0.0:50051
      - DATABASE_URL=postgres://postgres:pass@db:5432/cpass
    depends_on:
      - db
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]

  proxy_worker:
    image: ghcr.io/cyberfatherrt/cpass_proxy_worker
    build:
      context: proxy/nginx
      args:
        role: worker
    depends_on:
      - http
      - grpc
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]

  proxy_manager:
    image: ghcr.io/cyberfatherrt/cpass_proxy_manager
    build:
      context: proxy/haproxy
      args:
        role: manager
    ports:
      - 80:80
      - 443:443
      - 50051:50051
    depends_on:
      - proxy_worker
    deploy:
      placement:
        constraints: [node.role == manager]

  db:
    image: postgres:16.3-alpine3.20
    user: postgres
    environment:
      - POSTGRES_DB=cpass
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    deploy:
      placement:
        constraints: [node.role == manager]
